def afreq(sequence: str) -> int: ...
def all_contain(sequences: list[str], subsequence: str) -> bool: ...
def cbase(sequence: str) -> str: ...
def complement(sequence: str) -> str: ...
def ctable(sequence: str) -> str: ...
def delete(sequence: str, subsequence: str) -> str: ...
def is_dna(sequence: str) -> bool: ...
def is_protein(sequence: str) -> bool: ...
def is_rna(sequence: str) -> bool: ...
def mass(sequence: str) -> float: ...
def mtable(sequence: str) -> float: ...
def reverse(sequence: str) -> str: ...
def reverse_complement(sequence: str) -> str: ...
def shortest_seq(sequences: list[str]): ...
def transcribe(sequence: str) -> str: ...
def transcribe_back(sequence: str) -> str: ...
def translate_dna(sequence: str) -> str: ...
def translate_rna(sequence: str) -> str: ...
