def freq(sequence: str) -> dict: ...
def gc_content(sequence: str) -> float: ...
def hamming_distance(sequence1: str, sequence2: str) -> int: ...
def titv_ratio(sequence1: str, sequence2: str) -> float: ...
